[DEFAULT]
scheduling_interval = "1m"
requires = ["psutil"]

# retrieve uptime and temp from procfs / sysfs
[uptime]
func = "float(open('/proc/uptime').read().split()[0])"
[temperature]
func = "float(open('/sys/class/thermal/thermal_zone0/temp').read())/1000"
[rp1]
func = "float(open('/sys/class/hwmon/hwmon2/temp1_input').read())/1000"
[pmic]
func = "float(subprocess.check_output(['vcgencmd', 'measure_temp', 'pmic']).decode().split('=')[1].strip()[:-2])"
requires = ["subprocess"]

# get system information via psutil
[load]
func = "psutil.getloadavg()"
[memory]
func = "psutil.virtual_memory()"
[cpufreq]
func = "psutil.cpu_freq()"
[diskusage/data]
func = "psutil.disk_usage('/data')"

# get wireguard connection state
[ifaddr/wireguard]
scheduling_interval = "1h"
func = "psutil.net_if_addrs()['wireguard'][0]"

# get huawei status information
[huawei/information]
scheduling_interval = "1h"
requires = ["requests", "xml", "xml.etree", "xml.etree.ElementTree"]
func = "{elem.tag: elem.text for elem in xml.etree.ElementTree.fromstring(requests.get('http://192.168.8.1/api/device/information', timeout=1).content)}"

[huawei/signal]
scheduling_interval = "1h"
requires = ["requests", "xml", "xml.etree", "xml.etree.ElementTree"]
func = "{elem.tag: elem.text for elem in xml.etree.ElementTree.fromstring(requests.get('http://192.168.8.1/api/device/signal', timeout=1).content)}"

[huawei/current-plmn]
scheduling_interval = "1h"
requires = ["requests", "xml", "xml.etree", "xml.etree.ElementTree"]
func = "{elem.tag: elem.text for elem in xml.etree.ElementTree.fromstring(requests.get('http://192.168.8.1/api/net/current-plmn', timeout=1).content)}"

[huawei/net-mode]
scheduling_interval = "1h"
requires = ["requests", "xml", "xml.etree", "xml.etree.ElementTree"]
func = "{elem.tag: elem.text for elem in xml.etree.ElementTree.fromstring(requests.get('http://192.168.8.1/api/net/net-mode', timeout=1).content)}"

[huawei/traffic-statistics]
scheduling_interval = "1h"
requires = ["requests", "xml", "xml.etree", "xml.etree.ElementTree"]
func = "{elem.tag: elem.text for elem in xml.etree.ElementTree.fromstring(requests.get('http://192.168.8.1/api/monitoring/traffic-statistics', timeout=1).content)}"

# modemmanager status information
[modem]
requires = ["requests"]
func = 'requests.get("http://localhost/api/network/modem/").json()'
scheduling_interval = "1h"

# solar power via vedirect serial interface
[vedirect]
requires = ["vedirect_dump"]
func = 'vedirect_dump.query_device()'

# solar power via solarlife ble interface
[solarlife]
requires = ["solarlife", "solarlife.client"]
func = 'solarlife.client.read_device()'

# voltage via wittypi
[wittypi4]
requires = ["tsschedule", "tsschedule.backends.wittypi4"]
func = 'tsschedule.backends.wittypi4.WittyPi4().get_status()'

# configuration status
[tsconfig]
requires = ["requests"]
func = 'requests.get("http://localhost/api/configs/").json()'
scheduling_interval = "1h"

# os release
[release]
requires = ["dotenv"]
func = 'dotenv.dotenv_values("/etc/os-release")'
scheduling_interval = "1h"
