lat: 50.85318565
lon: 8.78743147
force_on: true
button_delay: 00:30
schedule:
- name: debugging
  start: sunrise+00:00
  stop: sunset-00:00
- name: owls
  start: sunset-00:30
  stop: sunrise+00:30
- name: birds morning song
  start: sunrise-01:00
  stop: sunrise+02:00
