# Static audio device list for server mode
# This file defines available audio devices that will be shown in the UI
# when tsconfig runs in server mode (where actual hardware cannot be queried)

input:
  - name: "trackIT Analog Frontend"
    max_input_channels: 2
    default_sample_rate: 384000
    is_default: true
  
  - name: "384kHz AudioMoth USB Microphone"
    max_input_channels: 1
    default_sample_rate: 384000
    is_default: false
  
  - name: "USB AUDIO DEVICE"
    max_input_channels: 2
    default_sample_rate: 48000
    is_default: false

output:
  - name: "bcm2835 Headphones"
    max_output_channels: 2
    default_sample_rate: 48000
    is_default: true
  
  - name: "USB AUDIO DEVICE"
    max_output_channels: 2
    default_sample_rate: 48000
    is_default: false
